# Generated by Django 4.1.4 on 2022-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_rename_username_request_to_chat_name1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_blocked', models.CharField(max_length=100)),
                ('blocked_by', models.CharField(max_length=100)),
            ],
        ),
    ]
