# Generated by Django 4.1.4 on 2023-01-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_remove_request_to_chat_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_to_chat',
            name='name2',
        ),
        migrations.AddField(
            model_name='request_to_chat',
            name='requestor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requestor', to='meet.profile'),
        ),
        migrations.AlterField(
            model_name='request_to_chat',
            name='acceptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_acceptor', to='meet.profile'),
        ),
    ]
