# Generated by Django 4.1.4 on 2023-01-09 18:37

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_message_delete_messgae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=100),
        ),
    ]
